### ISSUE TITLE
Replace with a `.find()`

### ISSUE THREAD

**Issue by ecumene** [SheldonT/Antenna-Length-Calculator#10]
https://github.com/SheldonT/Antenna-Length-Calculator/blob/95e703c605ad85938c1b26d174eac3bbb2bbef8a/index.html#L17

**Comment by ecumene** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by SheldonT** [comment]
Used function isChecked() to return the search criteria for antenna.find().
