### ISSUE TITLE
Fix: End path

### ISSUE THREAD

**Issue by ecumene** [SheldonT/Antenna-Length-Calculator#11]
https://github.com/SheldonT/Antenna-Length-Calculator/blob/95e703c605ad85938c1b26d174eac3bbb2bbef8a/index.html#L39

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/closePath

**Comment by SheldonT** [comment]
Drew each line starting with ctx.beginPath() and ending with ctx.closePath.
