### ISSUE TITLE
Implement a decimal root font size

### ISSUE THREAD

**Issue by ecumene** [SheldonT/Antenna-Length-Calculator#6]
```css
html {
    font-size: 10px;
}
```

 - [ ] Change all the usages of REM to be `0.63` -> `1`

**Comment by SheldonT** [comment]
Changed root font size to 10px, to change 1 rem to equal 10px rather than 16px.
Changed font size for the .main class to 1.6rem to make fonts look the same as before root font size was changed.
Converted all other rem measurements to reflect change in root font size.
